//
//  Lorem.swift
//  AutomaticPager
//
//  Created by Romain Menke on 20/09/15.
//  Copyright © 2015 menke dev. All rights reserved.
//

import Foundation


var lorem = ["Sinds enkele maanden woon ik opnieuw in Turnhout. ",
    "De dag nadat ik mijn vrouw heb begraven – dat gebeurde tijdens een sneeuwstorm begin januari – ben ik naar mijn geboortestad teruggekeerd. ",
    "Er was hier weinig veranderd. ",
    "Het slot van Maria van Brabant dreef nog steeds als een massief blok in een vierkante plas onder de naakte kilte rondom eeuwenoude loofbomen. ",
    "Bezijden hiervan loerde de zopas opgerichte nachtmerrie van elke speelse kwajongen zoals ik er in mijn jongste jaren niet minder eentje was: ",
    "de gestrenge klaslokalen gevat in het sombere bolwerk van het instituut der Broeders van Liefde. \r",
    "\tRijke patriciërswoningen met vlaggenmast schuin tegen de wit bepleisterde voorgevels in een versleten centrum. ",
    "Weinig straatverkeer. ",
    "Verder naar buiten: ",
    "een ordeloze troep wat sjofele huisjes in vuilrode werkmansbaksteen. ",
    "En daartussen verspreid: ",
    "de kleine en grote fabrieken waar papier verwerkt wordt tot speelkaarten, ",
    "bijbels, ",
    "missalen. ",
    "Lege, ",
    "bewegingloze straten. ",
    "Vlaams gekasseid, ",
    "zodat je elke hobbelende stootkar van ver hoort aankomen. ",
    "Het stadhuis bijna te midden van het marktplein met recht daartegenover de klokkenluidende torenspits van Sint-Pieter, ",
    "veelal onder een drijvende lage hemel van asgrauwe wolken. \r",
    "\tWaarom Turnhout? ",
    "Deze vergeetput. ",
    "Deze verste uithoek van het land. ",
    "Deze door erosie ingesleten straten waarvan de randen opgeslokt worden door een mosgroene mist van brabbelend koetervlaams, ",
    "gier, ",
    "varkensstallen, ",
    "achterlijkheid, ",
    "het verlaten geblèr van een koe. \r",
    "\tHaar uitgangswegen lopen niet verder dan een vergeten grenspost voorbij een boerengat als Arendonk of Poppel. \r",
    "\tOp andere plaatsen, ",
    "voornamelijk in grote steden, ",
    "is het een leven, ",
    "een tierlantijn en een drukte van jewelste! ",
    "Daar wordt de tango uitgevonden, ",
    "kan men de opera bezoeken, ",
    "lopen de eerste cinemazalen nokvol. \r",
    "\tJa, ",
    "hoe 't er in de grote wereld aan toe gaat, ",
    "daar weet ik wat van! ",
    "Mijn vrouw was een podiumdiva. ",
    "Daardoor heb ik Wenen bezocht, ",
    "en Praag. ",
    "In Düsseldorf heb ik een opvoering gezien van Franz Lehárs Die lustige Witwe. ",
    "Ik zat er op een bevoorrechte plaats. ",
    "Als ik mijn blik liet rondgaan, ",
    "zag ik niks dan blote ruggen van rijke matrones. ",
    "In de Parijse Opéra overkwam mij tijdens de pauze zelfs de eer om de roemruchte Franse dichter Guillaume Apollinaire de hand te drukken. ",
    "Maar als ik over al die dingen spreek, ",
    "dan heb ik het feitelijk over aankleding, ",
    "over froufrou, ",
    "over chichi, ",
    "ja, ",
    "over alles wat een mens verstrooit en te midden van een immense anonimiteit afleidt van zijn naakte zelf. \r",
    "\t't Is waarachtig zowel om de noodwendige terugkeer naar de eenvoud als om de zachte prijs van de kleine vrede en de innerlijke rust dat ik hier aanbelandde. ",
    "Zie, ",
    "achter deze vensters gebeurt werkelijk niets, ",
    "behalve het verschuiven van wolken, ",
    "van seizoenen, ",
    "van wisselende weersomstandigheden, ",
    "met de erosie van je nekvel tot gevolg. ",
    "Men kan hier kwaad om worden. ",
    "Moordlustig. ",
    "Chagrijnig. ",
    "Of opstandig. ",
    "Zo kan een man zich op een regenachtige zondagmiddag uit stomme verveling een stuk in de kraag drinken of met zijn hoofd tegen de muur beuken. ",
    "Baten doet het niet. ",
    "Om die reden houd ik me dagelijks voor dat een minder gewelddadig tijdverdrijf eveneens tot de mogelijkheden behoort. ",
    "In dat geval geeft men de lieve vrede en ook de verveling al braaf een handje. ",
    "Voilà, ",
    "nu weet ik ineens waaraan het spelletje 'Mens erger je niet!' zijn naam te danken heeft. \r",
    "\tIs men heel alleen, ",
    "een in zichzelf teruggetrokken, ",
    "kinderloze weduwnaar zoals ik, ",
    "dan kan men een boek van één van zijn favoriete schrijvers ter hand nemen. ",
    "Men is ook vrij om in zijn eentje patience te spelen en woordpuzzels of andere raadseltjes in te vullen. ",
    "Persoonlijk geef ik de voorkeur aan wat afwisseling, ",
    "zoals een lang hoofdstuk uit de laatste nieuwe van Louis Couperus, ",
    "gevolgd door een korte wandeling naar de Grote Markt. ",
    "Na twee of drie pintjes bij Charles Spruyt en wat kletsen aan de toog langs een omweg weer naar huis. ",
    "Een tweede hoofdstuk. ",
    "Avondmaal. ",
    "Als het stikdonker wordt de keet in. ",
    "En zo heel bescheiden op naar de volgende week, ",
    "naar de langzame winst van mijn achter het huis gelegen moestuintje. ",
    "Of het even langzame verlies van mijn leven gedurende vredestijd. \r",
    "\tWant strijd brengt toch niets dan miserie. ",
    "En ik kan het weten. ",
    "Ook al vertel ik geen hond waarom dat zo is. ",
    "De slagvelden of opstanden waar mensen elkaar als razende mieren bestormen en in mootjes hakken bestaan. ",
    "Vandaag – anno negentienhonderd en tien – vinden zij in Perzië plaats, ",
    "en wellicht in komende tijden elders, ",
    "of ook weer hier! ",
    "'t Is waar, ",
    "ik heb het al vaak genoeg in de gazetten gelezen: ",
    "sommige heethoofden worstelen nu al in 't geheim met hun broodheer op 't kasteeltje. ",
    "Wie een beetje voeling heeft met de tijd weet dat de kiem van dit geweld in het bijtende zuur van hun lege maag zit, ",
    "in hun vernedering en innerlijke tekorten. ",
    "Ik vraag me af of het allemaal wel zo schoon en nobel is, ",
    "maar als het vandaag hier te lande om klinkende woorden gaat, ",
    "of om slagzinnen, ",
    "dan worden zij aangereikt door de Vlaamse gedachte of het ideeëngoed van het socialisme. ",
    "Zo is er een stille revolutie aan de gang tegen de gevestigde financiële machten, ",
    "tegen de gehoorzaamheid aan de paapse kerk die ondanks zoveel ten hemel schreiende uitbuiting blijft vasthouden aan het lenigen van de nood door naastenliefde. ",
    "Ik beweer helemaal niet dat deze nieuwe oproerkraaiers ongelijk hebben. ",
    "Maar doordat wij er in deze straten voorlopig allemaal blank uitzien, ",
    "zijn hier, ",
    "laat ons zeggen, ",
    "alvast nog geen rassenonlusten zoals in Amerika. \r",
    "\t'Wij mogen niet klagen,' beweerde mijn moeder zaliger altijd op schemeruur, ",
    "voor ze haar oude hoofd ter ruste legde. ",
    "'Het lot kan altijd nog een stukje vreselijker. ",
    "En… hé…' \r",
    "\t'Wat wou je zeggen, ",
    "Moe?' \r",
    "\t'Welja, ",
    "Janus! ",
    "Het is toch allemaal zoals het eruitziet! ",
    "Of niet?' \r",
    "\tIk herinner me deze wijze woorden. ",
    "Ik beaamde haar groot gelijk altijd met een overtuigd knikje, ",
    "ook al had ik in mijn jonge jaren niet het geringste besef dat het lot en de wereld geen rekening houden met 's mans persoonlijke wens hoe alles er zou moeten uitzien. ",
    "En ondertussen geef ik op mijn beurt plaats aan het onvermijdelijke. ",
    "Want inderdaad: ",
    "feiten doen zich voor als feiten. ",
    "Een mens kan daar niet omheen. ",
    "Hoe iets er ook uitziet, ",
    "het is altijd zoals het is. \r",
    "\tDat mijn moeder er warmpjes bij zat, ",
    "is zo'n onwrikbaar gegeven. ",
    "Toen zij vorig jaar zonder één klacht haar hoofd definitief ter ruste legde, ",
    "bleek ik niet enkel de enige erfgenaam van drie behoorlijk onderhouden Turnhoutse patriciërswoningen. ",
    "In het naburige Gierle bezat zij uitgestrekte landbouwgronden waarvan nog steeds grote delen aan de plaatselijke boeren worden verpacht. \r",
    "\tNadat notaris Onckelinx mij hiervan formeel op de hoogte had gebracht, ",
    "overhandigde hij me een rood gelakt, ",
    "houten kistje. ",
    "'Open dit thuis maar,' zei hij. \r",
    "\tIk wachtte tot ik heel alleen in mijn Rotterdamse woonkamer stond om geconfronteerd te worden met wat is geweest. ",
    "Tussen allerlei spullen op de bodem van de kist lagen de schoolschriften van mijn twee jaar jongere broertje Waldo. \r",
    "\tHet ventje was nog altijd negen en in mijn herinnering even gaaf als zijn afgeknipte, ",
    "bruinzwarte haarlok in een dichtgeplooide briefomslag. "]